# Azure Static Web Apps deployment pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # Add your Azure Static Web App deployment token as a pipeline variable
  # You'll need to set this in Azure DevOps Pipeline Library
  azureStaticWebAppsToken: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'

stages:
- stage: Build
  displayName: 'Build and Deploy'
  jobs:
  - job: BuildAndDeploy
    displayName: 'Build and Deploy Job'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    
    - script: |
        npm install
      displayName: 'Install dependencies'
    
    - script: |
        npm run build
      displayName: 'Build application'
    
    - task: AzureStaticWebApp@0
      inputs:
        app_location: '/'
        api_location: ''
        output_location: 'dist'
        skip_app_build: true
        deployment_token: $(azureStaticWebAppsToken)
      displayName: 'Deploy to Azure Static Web App' 